### ISSUE TITLE
Hey, may I know the course you are studying？

### ISSUE THREAD

**Issue by xdai555** [mfeindt0705/nornirclass#1]

**Comment by mfeindt0705** [comment]
Hi, I subscribed to the Nornir training of Kirk Byers
https://pynet.twb-tech.com/class-nornir.html

**Comment by odai5** [comment]
OK, thanks . I have noticed this course before ,but I think it is difficute for me to understand teacher's words in calss . （I am a Chinese, English is not my native language..... ）
BTW, Is it a live course? Is there a video recording?
